/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-03-01 at 09:46:10 UTC 
 * Modify at your own risk.
 */

package com.example.gossip.gossipmessageendpoint;

/**
 * Service definition for Gossipmessageendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GossipmessageendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Gossipmessageendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the gossipmessageendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "gossipmessageendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Gossipmessageendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Gossipmessageendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getGossipMessage".
   *
   * This request holds the parameters needed by the the gossipmessageendpoint server.  After setting
   * any optional parameters, call the {@link GetGossipMessage#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetGossipMessage getGossipMessage(java.lang.Long id) throws java.io.IOException {
    GetGossipMessage result = new GetGossipMessage(id);
    initialize(result);
    return result;
  }

  public class GetGossipMessage extends GossipmessageendpointRequest<com.example.gossip.gossipmessageendpoint.model.GossipMessage> {

    private static final String REST_PATH = "gossipmessage/{id}";

    /**
     * Create a request for the method "getGossipMessage".
     *
     * This request holds the parameters needed by the the gossipmessageendpoint server.  After
     * setting any optional parameters, call the {@link GetGossipMessage#execute()} method to invoke
     * the remote operation. <p> {@link GetGossipMessage#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetGossipMessage(java.lang.Long id) {
      super(Gossipmessageendpoint.this, "GET", REST_PATH, null, com.example.gossip.gossipmessageendpoint.model.GossipMessage.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGossipMessage setAlt(java.lang.String alt) {
      return (GetGossipMessage) super.setAlt(alt);
    }

    @Override
    public GetGossipMessage setFields(java.lang.String fields) {
      return (GetGossipMessage) super.setFields(fields);
    }

    @Override
    public GetGossipMessage setKey(java.lang.String key) {
      return (GetGossipMessage) super.setKey(key);
    }

    @Override
    public GetGossipMessage setOauthToken(java.lang.String oauthToken) {
      return (GetGossipMessage) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGossipMessage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGossipMessage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGossipMessage setQuotaUser(java.lang.String quotaUser) {
      return (GetGossipMessage) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGossipMessage setUserIp(java.lang.String userIp) {
      return (GetGossipMessage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetGossipMessage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetGossipMessage set(String parameterName, Object value) {
      return (GetGossipMessage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertGossipMessage".
   *
   * This request holds the parameters needed by the the gossipmessageendpoint server.  After setting
   * any optional parameters, call the {@link InsertGossipMessage#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.example.gossip.gossipmessageendpoint.model.GossipMessage}
   * @return the request
   */
  public InsertGossipMessage insertGossipMessage(com.example.gossip.gossipmessageendpoint.model.GossipMessage content) throws java.io.IOException {
    InsertGossipMessage result = new InsertGossipMessage(content);
    initialize(result);
    return result;
  }

  public class InsertGossipMessage extends GossipmessageendpointRequest<com.example.gossip.gossipmessageendpoint.model.GossipMessage> {

    private static final String REST_PATH = "gossipmessage";

    /**
     * Create a request for the method "insertGossipMessage".
     *
     * This request holds the parameters needed by the the gossipmessageendpoint server.  After
     * setting any optional parameters, call the {@link InsertGossipMessage#execute()} method to
     * invoke the remote operation. <p> {@link InsertGossipMessage#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.gossip.gossipmessageendpoint.model.GossipMessage}
     * @since 1.13
     */
    protected InsertGossipMessage(com.example.gossip.gossipmessageendpoint.model.GossipMessage content) {
      super(Gossipmessageendpoint.this, "POST", REST_PATH, content, com.example.gossip.gossipmessageendpoint.model.GossipMessage.class);
    }

    @Override
    public InsertGossipMessage setAlt(java.lang.String alt) {
      return (InsertGossipMessage) super.setAlt(alt);
    }

    @Override
    public InsertGossipMessage setFields(java.lang.String fields) {
      return (InsertGossipMessage) super.setFields(fields);
    }

    @Override
    public InsertGossipMessage setKey(java.lang.String key) {
      return (InsertGossipMessage) super.setKey(key);
    }

    @Override
    public InsertGossipMessage setOauthToken(java.lang.String oauthToken) {
      return (InsertGossipMessage) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertGossipMessage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertGossipMessage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertGossipMessage setQuotaUser(java.lang.String quotaUser) {
      return (InsertGossipMessage) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertGossipMessage setUserIp(java.lang.String userIp) {
      return (InsertGossipMessage) super.setUserIp(userIp);
    }

    @Override
    public InsertGossipMessage set(String parameterName, Object value) {
      return (InsertGossipMessage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listGossipMessage".
   *
   * This request holds the parameters needed by the the gossipmessageendpoint server.  After setting
   * any optional parameters, call the {@link ListGossipMessage#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListGossipMessage listGossipMessage() throws java.io.IOException {
    ListGossipMessage result = new ListGossipMessage();
    initialize(result);
    return result;
  }

  public class ListGossipMessage extends GossipmessageendpointRequest<com.example.gossip.gossipmessageendpoint.model.CollectionResponseGossipMessage> {

    private static final String REST_PATH = "gossipmessage";

    /**
     * Create a request for the method "listGossipMessage".
     *
     * This request holds the parameters needed by the the gossipmessageendpoint server.  After
     * setting any optional parameters, call the {@link ListGossipMessage#execute()} method to invoke
     * the remote operation. <p> {@link ListGossipMessage#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListGossipMessage() {
      super(Gossipmessageendpoint.this, "GET", REST_PATH, null, com.example.gossip.gossipmessageendpoint.model.CollectionResponseGossipMessage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListGossipMessage setAlt(java.lang.String alt) {
      return (ListGossipMessage) super.setAlt(alt);
    }

    @Override
    public ListGossipMessage setFields(java.lang.String fields) {
      return (ListGossipMessage) super.setFields(fields);
    }

    @Override
    public ListGossipMessage setKey(java.lang.String key) {
      return (ListGossipMessage) super.setKey(key);
    }

    @Override
    public ListGossipMessage setOauthToken(java.lang.String oauthToken) {
      return (ListGossipMessage) super.setOauthToken(oauthToken);
    }

    @Override
    public ListGossipMessage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListGossipMessage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListGossipMessage setQuotaUser(java.lang.String quotaUser) {
      return (ListGossipMessage) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListGossipMessage setUserIp(java.lang.String userIp) {
      return (ListGossipMessage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListGossipMessage setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListGossipMessage setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListGossipMessage set(String parameterName, Object value) {
      return (ListGossipMessage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeGossipMessage".
   *
   * This request holds the parameters needed by the the gossipmessageendpoint server.  After setting
   * any optional parameters, call the {@link RemoveGossipMessage#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveGossipMessage removeGossipMessage(java.lang.Long id) throws java.io.IOException {
    RemoveGossipMessage result = new RemoveGossipMessage(id);
    initialize(result);
    return result;
  }

  public class RemoveGossipMessage extends GossipmessageendpointRequest<Void> {

    private static final String REST_PATH = "gossipmessage/{id}";

    /**
     * Create a request for the method "removeGossipMessage".
     *
     * This request holds the parameters needed by the the gossipmessageendpoint server.  After
     * setting any optional parameters, call the {@link RemoveGossipMessage#execute()} method to
     * invoke the remote operation. <p> {@link RemoveGossipMessage#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveGossipMessage(java.lang.Long id) {
      super(Gossipmessageendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveGossipMessage setAlt(java.lang.String alt) {
      return (RemoveGossipMessage) super.setAlt(alt);
    }

    @Override
    public RemoveGossipMessage setFields(java.lang.String fields) {
      return (RemoveGossipMessage) super.setFields(fields);
    }

    @Override
    public RemoveGossipMessage setKey(java.lang.String key) {
      return (RemoveGossipMessage) super.setKey(key);
    }

    @Override
    public RemoveGossipMessage setOauthToken(java.lang.String oauthToken) {
      return (RemoveGossipMessage) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveGossipMessage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveGossipMessage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveGossipMessage setQuotaUser(java.lang.String quotaUser) {
      return (RemoveGossipMessage) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveGossipMessage setUserIp(java.lang.String userIp) {
      return (RemoveGossipMessage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveGossipMessage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveGossipMessage set(String parameterName, Object value) {
      return (RemoveGossipMessage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateGossipMessage".
   *
   * This request holds the parameters needed by the the gossipmessageendpoint server.  After setting
   * any optional parameters, call the {@link UpdateGossipMessage#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.example.gossip.gossipmessageendpoint.model.GossipMessage}
   * @return the request
   */
  public UpdateGossipMessage updateGossipMessage(com.example.gossip.gossipmessageendpoint.model.GossipMessage content) throws java.io.IOException {
    UpdateGossipMessage result = new UpdateGossipMessage(content);
    initialize(result);
    return result;
  }

  public class UpdateGossipMessage extends GossipmessageendpointRequest<com.example.gossip.gossipmessageendpoint.model.GossipMessage> {

    private static final String REST_PATH = "gossipmessage";

    /**
     * Create a request for the method "updateGossipMessage".
     *
     * This request holds the parameters needed by the the gossipmessageendpoint server.  After
     * setting any optional parameters, call the {@link UpdateGossipMessage#execute()} method to
     * invoke the remote operation. <p> {@link UpdateGossipMessage#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.gossip.gossipmessageendpoint.model.GossipMessage}
     * @since 1.13
     */
    protected UpdateGossipMessage(com.example.gossip.gossipmessageendpoint.model.GossipMessage content) {
      super(Gossipmessageendpoint.this, "PUT", REST_PATH, content, com.example.gossip.gossipmessageendpoint.model.GossipMessage.class);
    }

    @Override
    public UpdateGossipMessage setAlt(java.lang.String alt) {
      return (UpdateGossipMessage) super.setAlt(alt);
    }

    @Override
    public UpdateGossipMessage setFields(java.lang.String fields) {
      return (UpdateGossipMessage) super.setFields(fields);
    }

    @Override
    public UpdateGossipMessage setKey(java.lang.String key) {
      return (UpdateGossipMessage) super.setKey(key);
    }

    @Override
    public UpdateGossipMessage setOauthToken(java.lang.String oauthToken) {
      return (UpdateGossipMessage) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateGossipMessage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateGossipMessage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateGossipMessage setQuotaUser(java.lang.String quotaUser) {
      return (UpdateGossipMessage) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateGossipMessage setUserIp(java.lang.String userIp) {
      return (UpdateGossipMessage) super.setUserIp(userIp);
    }

    @Override
    public UpdateGossipMessage set(String parameterName, Object value) {
      return (UpdateGossipMessage) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Gossipmessageendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Gossipmessageendpoint}. */
    @Override
    public Gossipmessageendpoint build() {
      return new Gossipmessageendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GossipmessageendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGossipmessageendpointRequestInitializer(
        GossipmessageendpointRequestInitializer gossipmessageendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(gossipmessageendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
